### ISSUE TITLE
Not working since Alpine image

### ISSUE THREAD

**Issue by crazy-max** [dperson/samba#109]
Hi @dperson,

First of all thanks for your work on this docker image!
Since [the conversion from debian to alpine image](https://github.com/dperson/samba/commit/e6db04336bde974007f30441805b21f0aef8a4ca), samba is not working anymore.

So i have built an image from commit f76146635c0949af69287933406411209e1b8184 and everything works fine.

Here is my docker-compose :

```
version: '3'

services:
  samba:
    image: dperson/samba
    container_name: samba
    network_mode: host
    ports:
      - 137-139:137-139
      - 445:445
      - 137:137/udp
      - 138:138/udp
    volumes:
      - /mnt/crazy:/samba/crazy
      - /mnt/public:/samba/public
      - /etc/localtime:/etc/localtime:ro
    entrypoint:
      - samba.sh
      - -g
      - netbios name=CRAZYNAS
      - -g
      - guest account=nobody
      - -g
      - force user=crazy
      - -g
      - force group=crazy
      - -n
      - -r
      - -w
      - WORKGROUP
      - -s
      - public;/samba/public
      - -s
      - crazy;/samba/crazy;yes;no;no;crazy;none;crazy
      - -u
      - crazy;password;1000;crazy
      - -W
    restart: always
```

And logs :

```
nas-samba | adduser: uid '1000' in use
nas-samba | Failed to add entry for user crazy.
nas-samba | [2018/01/07 20:58:38.584809,  0] ../lib/util/become_daemon.c:124(daemon_ready)
nas-samba |   STATUS=daemon 'nmbd' finished starting up and ready to serve connections
nas-samba | smbd version 4.7.3 started.
nas-samba | Copyright Andrew Tridgell and the Samba Team 1992-2017
nas-samba | STATUS=daemon 'smbd' finished starting up and ready to serve connections
```
