### ISSUE TITLE
Cant access share with password

### ISSUE THREAD

**Issue by lbormann** [dperson/samba#141]
hi, anytime i try to access a shared folder from windows-10 it says wrong password.

my setup for runnning samba:
newest docker-ce on debian-9
running as root

my docker-compose.yml:

```
version: '3'

services:
  samba:
    image: dperson/samba
    command: -u "root;root;0;0" -s "public;/mount/public;yes;no;yes" -s "priv;/mount/priv;yes;no;no"
    restart: always
    volumes:
      - /storage/Seagate-ST4000VN000-1/docker/volumes/samba:/mount
    ports:
      - 139:139
      - 445:445
```

BTW: Shares without a password works fine! Please help!

**Comment by Strayer** [comment]
I first assumed that root is some special case for samba, but this is working fine for me:

```yaml
# docker-compose.yml
version: '3.4'

services:
  samba:
    build: .
    environment:
      TZ: 'Europe/Berlin'
    tmpfs:
      - /tmp
      - /run
      - /var/cache/samba/
      - /var/log/samba/
    restart: unless-stopped
    volumes:
      - ./testmnt:/mnt/testmnt
      - samba-lib:/var/lib/samba
    command: '-u "root;root;0;0" -s "Test;/mnt/testmnt;yes;no;no"'
  client:
    image: alpine:edge
    entrypoint: ["sh", "-c"]
    command: "'apk add --no-cache samba bash; exec bash'"

volumes:
  samba-lib:
```

```
# docker-compose run --rm client
bash-4.4# smbclient '\\samba\Test' -U 'root'
Enter MYGROUP\root's password:
Try "help" to get a list of possible commands.
smb: \> ls
  .                                   D        0  Tue Jun 19 19:20:41 2018
  ..                                  D        0  Tue Jun 19 19:49:40 2018
  test.txt                            N        5  Tue Jun 19 19:20:41 2018
```

Are you sure the permissions on the mounted volumes are correct? Any error messages when trying to access the share with smbclient like I did above?
