### ISSUE TITLE
Command Block Entries in Compose Reporting "illegal character with code 32 at position 0"

### ISSUE THREAD

**Issue by megavaughn** [dperson/samba#163]
Hello and thanks for the rad Samba image!

I'm running on latest Docker via Ubuntu Server 16.04 LTS and whenever I use a command entry to send off a parameter to the samba container I get the following error (in this case a user addition):

> samba_1  | adduser: illegal character with code 32 at position 0
> samba_1  | Failed to add entry for user  USERNAME.

**NOTE: I'm not sure if it's coming through here in this post due to formatting but there is an additional space in front of USERNAME. Pretty sure this is what's causing the parser to freak out.**

My command entry for this in docker-compose.yaml looks like this:

```
    command:
      - "-u USERNAME;pass1234;1001;1001"
```

This same problem happens for any command entry. I tried single versus double quotes, etc. What does work is putting the equivalent command into the environment block:

`      - "USER=USERNAME;pass1234;1001;1001"`

With that samba reports:

> samba_1  | Added user USERNAME.

This is the case for any command using the command line (i.e. -s for share definitions etc).

I'm fully willing to accept this could be a noob mistake! 🥇 

Here is my full docker-compose file if it helps!

```
version: '3'
services:
  samba:
    image: dperson/samba:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - "NMBD=True"
      - "RECYCLE=False"
      - "WORKGROUP=abc"
# Uncomment to get adding users to work
#      - "USER=USERNAME;pass1234;1001;1001"

    networks:
      - default
    volumes:
#  Cannot set your own mount for samba directory
#  bummer because this could leave orphaned volumes...
#      - ./samba:/etc/samba
      - backup-USERNAME:/mnt/USERNAME/backups:ro
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    command:
      - "-u USERNAME;pass1234;1001;1001"
      - "-s backup-USERNAME;/mnt/USERNAME/backups;yes;yes;no;USERNAME"

volumes:
  backup-USERNAME:
    external: true
```
