### ISSUE TITLE
permission issue

### ISSUE THREAD

**Issue by IceflowRE** [dperson/samba#196]
my docker-compose.yml
```
version: '3.7'

services:
  samba:
    image: dperson/samba
    command: -p -u "iceflower;password;82;82" -s "data;/mnt/data;yes;no;no;iceflower"
    restart: always
    volumes:
      - type: bind
        source: /extdata/data
        target: /mnt/data
    ports:
      - "139:139"
      - "445:445"
#    environment:
#      - USERID=82
#      - GROUPID=82
```
My mounted folder and all files in it are owned by `82:82`.

If i try to access it with windows i get:
```
Windows cannot access \\server\data

You do not have the permission to access \\server\data.
```

The general connection works, as i tried it with another location like `-s "test;/test` 

After hours of trying i have no clue how i can fix it.

**Comment by IceflowRE** [comment]
```
version: '3.7'

services:
  samba:
    image: dperson/samba
    command: -p -u "iceflower;password" -s "data;/mnt/data;yes;no;no;iceflower"
    restart: always
    volumes:
      - type: bind
        source: /extdata/data
        target: /mnt/data
    ports:
      - "139:139"
      - "445:445"
    environment:
      - USERID=82
      - GROUPID=82
```

Did the job.
