### ISSUE TITLE
smbpasswd not working

### ISSUE THREAD

**Issue by me1299** [dperson/samba#203]
I've been trying for a few hours to get the smbpasswd feature to work. There is not much documentation available.

This is my compose file:

```
  samba:
    image: dperson/samba
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - WORKGROUP=workgroup
    volumes:
      - /media/usb/downloads:/downloads
      - ${USERDIR}/docker/shared:/shared
    command: '-i /shared/smbpasswd -s "Downloads;/downloads;no;no;no;all;myusername"'

```
I've put my generated smbpasswd file in ${USERDIR}/docker/shared. I can see the file in the docker container just fine.

When I view the smb.conf in the container:
`sudo docker exec -it samba cat /etc/samba/smb.conf |grep smbpasswd`

There is not mention of my smbpasswd file. It is not used at all. What am I doing wrong? A little more documentation would be helpful.
