### ISSUE TITLE
standard input is not a socket, assuming -D option

### ISSUE THREAD

**Issue by btheu** [dperson/samba#21]
Hi,

After last update i have now this error.

`docker run --name samba --rm -it -p 139:139 -p 445:445 dperson/samba -s "public;/tmp;yes;no;yes;all"`

```
samba_1        | smbd version 4.1.17-Debian started.
samba_1        | Copyright Andrew Tridgell and the Samba Team 1992-2013
samba_1        | standard input is not a socket, assuming -D option
```
Docker versions

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:42 2016
 OS/Arch:      linux/amd64
```

**Comment by btheu** [comment]
the error occurs only with docker-compose

```
  samba:
    image: dperson/samba
    restart: always
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - /data/docker:/share
    entrypoint:
      - samba.sh
      - -s 
      - "public;/share;yes;no;yes;all"
```

```
# docker-compose version
docker-compose version 1.7.0, build 0d7bf73
docker-py version: 1.8.0
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
```
