### ISSUE TITLE
how to set a share to read/write

### ISSUE THREAD

**Issue by jowo19** [dperson/samba#217]
Hi,
I am using dperson/samba on an ubuntu server 18lts in parallels desktop on a macbook with an own IP via docker-compose.yml:

```
version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - samba-network
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/joerg/mnt/media:/mnt/media:z
      - /home/joerg/mnt/timemachine:/mnt/timemachine:z
    command: '-s "Media;/mnt/media"  -s "TimeMachine;/mnt/timemachine;yes;no;no;joerg" -u "joerg;j1234"'

networks:
  smaba-network:
    driver: bridge
```

Mounts on the same ubuntu server (see above):
joerg@ubu01:~/mnt$ ls -la
insgesamt 20
drwxrwxr-x 4 joerg joerg 4096 Jul  8 18:09 .
drwxr-xr-x 7 joerg joerg 4096 Jul  7 19:59 ..
drwxrwxr-x 2 joerg joerg 4096 Jul  6 17:10 media
drwxrwxr-x 3 joerg joerg 4096 Jul  8 17:29 timemachine

I can connect to the samba service. The mounts Media and TimeMachine ocurres (windows pc, another mac).
But only as read only. Media is okay but not TimeMachine.
I had open a shell at the docker dperson/samba container.
I see the volumes and can write to it. The user joerg was added in the container as 1000:1000.

What am I doing wrong?
