### ISSUE TITLE
Getting error after latest update

### ISSUE THREAD

**Issue by eflemingtra** [dperson/samba#218]
Hi, seeing an error causing the docker container not to load correctly:

```
/usr/bin/samba.sh: line 245: syntax error near unexpected token `<(env | awk '/^GLOBAL/ {sub (/^[^=]*=/, "", $0); print}')',
/usr/bin/samba.sh: line 245: `done <(env | awk '/^GLOBAL/ {sub (/^[^=]*=/, "", $0); print}')',
```

I haven't made any changes to my docker compose for Samba that I can think of. My docker compose for Samba is as follows:

```
samba:  
    image: dperson/samba  
    container_name: samba  
    ports:  
      - "137:137/udp"  
      - "138:138/udp"  
      - "139:139/tcp"  
      - "445:445/tcp"  
    restart: always
    environment:  
      - TZ=Australia/Sydney 
      - PUID=1000
      - PGID=999
      - USER=username;password
      - SHARE=Server;/server;yes;no;no;;gerben  
    volumes:  
      - /home/user/docker:/server   
```
