### ISSUE TITLE
/usr/bin/samba.sh: line 140: $2: unbound variable

### ISSUE THREAD

**Issue by millermarkj** [dperson/samba#219]
I use v2tec/watchtower to keep my containers updated. samba updated last night and now won't run. Starting it manually reports:

```
mark@system:/opt/svc/samba$ docker-compose up
Recreating samba_samba_1 ... done
Attaching to samba_samba_1
samba_1  | /usr/bin/samba.sh: line 140: $2: unbound variable
samba_samba_1 exited with code 1
```

Based on a [prior issue](https://github.com/dperson/samba/issues/212) I double-checked the syntax. But nothing seems to make it start. My docker-compose file:

```
version: "3"
services:
  samba:
    image: "dperson/samba"
    restart: always
    ports:
      - 139:139
      - 137-138:137-138/udp
      - 445:445
    volumes:
      - "/volume1:/volume1:ro"
      - "/volume2:/volume2"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - backend
    environment:
      - USERID="1005"
      - GROUPID="30"
      - TZ=EST5EDT
    command: '-r -s "volume1;/volume1"
                 -s "volume2;/volume2"'
    labels:
      - com.centurylinklabs.watchtower.enable=true
networks:
  backend:
    external: true
```
