### ISSUE TITLE
Write permissions don't work after recreating container.

### ISSUE THREAD

**Issue by Dodgexander** [dperson/samba#229]
My config:
```
    samba:
        image: dperson/samba:latest
        container_name: samba
        command: >
            -w "WORKGROUP"
            -s "downloads;/downloads;yes;yes;yes;all;none;;comment1"
            -s "media;/media;yes;yes;yes;all;none;;comment2"
            -s "user;/user;yes;no;yes;all;none;;comment3"
            -s "uploads;/uploads;yes;no;yes;all;none;;comment3"
            -g "bind interfaces only = yes"
            -g "interfaces = lo enp*"
        environment:
            - USERID=1000
            - GROUPID=1000
            - NMBD=True
            - RECYCLE=False
        volumes:
            - /mnt/data/downloads:/downloads
            - /mnt/data/media:/media
            - /mnt/data/user:/user
            - /mnt/data/uploads:/uploads
        network_mode: host
        ports:
            - "139:139"
            - "445:445"
        restart: unless-stopped

```
If I choose later to add or remove a share or volume, write permission never works. I have to delete docker container and volumes and recreate from scratch.

The new folders are visible by clients, and the folder previously set with the same permission **does** allow write, just not the newest.

**Comment by Dodgexander** [comment]
Worked out it was a permission issue. Gotta try figure out why it is when docker creates files and folders they are given root permissions when I have pointed the UID and GID to my user.

**Comment by dperson** [comment]
Docker runs as root, so the things it does get run as that user (including directory creation). I added the `-p` (fix permissions) command line option to the container quite a while ago to set the permissions on startup.

**Comment by signedav** [comment]
`-p` set's the permission regarding the `PERMISSIONS` environment variable, right? How should this variable look like? When I set `dave:dave` for the user dave and the group dave, it still has the permissions on the shared folder on "smbuser:users"... When I use no `-p`, root is the owner.

```
  samba:
    image: dperson/samba
    restart: always
    ports:
      - '1399:139'
      - '4455:445'
    environment:
      - PERMISSIONS=dave:dave
    command: 
      -g "force user = dave"  
      -g "force group = dave" 
      -u "dave;dave123" 
      -s "projects;/projects;no;no;no;dave"
      -p 
      volumes:
      - './dave/projects:/projects'
    networks:
     - net
```

The command `chown -R dave:dave projects` would solve it. But I want to have it in the docker-compose file...
