### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by jamyouss** [dperson/samba#23]
Hi,

i actually use your image to be able to mount some volumes with docker compose on my mac os x.
```
samba:
        image: dperson/samba
        command: -u "root;root" -s "config;/config" -s "data;/data" -s "log;/log"
        restart: always
        ports:
            - "139:139"
            - "445:445"
        volumes:
            - data:/data
            - config:/config
            - log:/log
```

The problem is that data are in read only :-(
It's strange that permissions for all data is 700.

Any idea ?
