### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by FezVrasta** [dperson/samba#231]
Hi, I have a DietPI installation on a Raspberry Pi 4.

I'm running your container with `docker-compose`:

```yml
  samba:
    image: dperson/samba
    container_name: samba
    volumes:
      - /mnt/4tbdrive:/data
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    command: '-s "Data;/data;yes;no;no;dietpi" -u "dietpi;password"'
```

it runs without errors, but on either my macOS or SHIELD TV (Android) I can't connect.

I don't receive any specific error so it's quite difficult to debug the problem, there aren't errors neither on the client or the server.

on macOS I can see the "dietpi" Samba share, but it's empty.

I also tried to add this config but nothing changes:

```
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
```

May you help me understand what's going on?
