### ISSUE TITLE
Question about User / Permissions

### ISSUE THREAD

**Issue by tommyknows** [dperson/samba#236]
Hi,
I'm trying to run this container in a Kubernetes Pod, mounting the hostPath to the volume.
My podSpec currently looks like this:
```
      containers:
      - image: dperson/samba
        name: samba-server
        args:
          - -p
          - -s
          - "share;/mount;yes;no;yes
        env:
          - name: USERID
            value: "1012"
          - name: GROUPID
            value: "1111"
        ports:
          - name: one
            containerPort: 139
          - name: two
            containerPort: 445
        volumeMounts:
          - name: backup
            mountPath: /backup
      volumes:
        - name: backup
          hostPath:
            path: /mnt/data/backup/
            type: Directory
```

The UserID `1012` is mapped to a user that already exists on the machine called `smb`, the group is called `share`. 

What I am trying to achieve is that the share is mountable by `guest`, but on the local machine, the directory is written by the `smb` user in the `share` group.
Just setting the `USERID` and `GROUPID` does not work - when I write a file to the share, it is written as `root`.

Is it possible to execute the write-operations as the specified user & group?

I tried running the container as that user (through `podSecurityPolicies`), but then the container does not work at all.
I also tried "adding" a smb-user (with `-u`), but as the user and group already exists, this does not work either. I would be okay with deleting the user and having it created through the container, but the `share` group already exists for sure.

Thanks

**Comment by dperson** [comment]
I've never used Kubernetes... but the pod spec looks pretty straight forward and to be correct.

Is there any way to execute a shell inside the container (if so please run `id smbuser` in it), or is there any way to get the logs output to the console while the container is starting up (if so please upload them here)?

**Comment by tommyknows** [comment]
Alright, no worries. The translation of a container is more or less 1:1 to docker concepts, so it's not too hard :-)

Yes to both. 
Shell Output:
```
/ # id smbuser
uid=1012(smbuser) gid=101(smb) groups=101(smb),101(smb)
```

And the logs:
```
smbd version 4.10.5 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
```

**Comment by tommyknows** [comment]
Nevermind, it was actually working!
I did not sync the mountPoint and the actual share location properly (duh.).

Writes are now done through the proper user and group.

For everybody else, I got it working with the following deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: samba
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: samba
    spec:
      containers:
      - image: dperson/samba
        name: samba-server
        args:
          - -p
          - -s
          - "backup;/backup;yes;no;yes"
        env:
          - name: USERID
            value: "1012"
          - name: GROUPID
            value: "1111"
        ports:
          - name: one
            containerPort: 139
          - name: two
            containerPort: 445
        volumeMounts:
          - name: backup
            mountPath: /backup
      volumes:
        - name: backup
          hostPath:
            path: /mnt/data/backup/
            type: Directory
```

**Comment by dperson** [comment]
Glad to hear it!

**Comment by proclia** [comment]
@tommyknows How does the services look like for this dperson/samba. Are you literally using one of the pods as a file server?

**Comment by tommyknows** [comment]
Yes, I do. As I'm running this on a single node "cluster", I just use the HostVolume. With multiple nodes, you should use a Persistent Volume.
In front of that pod there's a Service with Type LoadBalancer, which is then my Samba endpoint I can connect to.

**Comment by proclia** [comment]
@tommyknows  Oh man, i badly need it, can you please give me `.yaml` files for `persistent volume` and `persistent volume claim` and `services` and `deployment` as well. Please.

**Comment by tommyknows** [comment]
😄  well I can't give you the PV & PVC definition as I don't use them.

<details><summary>Deployment</summary><br>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: samba
  name: samba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samba
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: samba
    spec:
      containers:
      - image: dperson/samba
        name: samba-server
        resources:
          limits:
            cpu: 200m
            memory: 500Mi
        args:
          # disable recycle bin
          - -r
          - -s
          - "backup;/backup;yes;yes;no;all;none;myuser"
          - -s
            # readonly for guest, rw for me
          - "media;/media;yes;yes;yes;all;none;myuser"
          - -u
          - "myuser;$MYPASSWD"
        env:
          - name: USERID
            value: "1012"
          - name: GROUPID
            value: "1111"
          - name: MYPASSWD
            valueFrom:
              secretKeyRef:
                name: smb-logins
                key: myuser
        ports:
          - name: one
            containerPort: 139
          - name: two
            containerPort: 445
        volumeMounts:
          - name: backup
            mountPath: /backup
          - name: media
            mountPath: /media
      volumes:
        - name: backup
          hostPath:
            path: /mnt/data/backup/
            type: Directory
        - name: media
          hostPath:
            path: /mnt/data/media
            type: Directory
```
</details>

<details><summary>Service</summary><br>

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: samba
  name: samba
  annotations:
    metallb.universe.tf/allow-shared-ip: "main"
spec:
  ports:
  - name: one
    port: 139
    protocol: TCP
    targetPort: 139
  - name: two
    port: 445
    protocol: TCP
    targetPort: 445
  selector:
    app: samba
  type: LoadBalancer
status:
  loadBalancer: {}
```

</details>

<details><summary>Secret</summary><br>

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: smb-logins
type: Opaque
data:
  myuser: <base64-encoded password>
```
</details>
