### ISSUE TITLE
GROUPID not applied on mounted volume

### ISSUE THREAD

**Issue by tomsquest** [dperson/samba#251]
Hi David,

I started using your image and I noticed a strange behavior with the GROUPID not being respected for the base directory.

Problem: after starting the container, my `/storage` folder is own by group `101` instead of 1000 (as per the GROUPID). 
The USERID is applied correctly.

```
$ stat /storage/
  File: /storage/
Access: (0775/drwxrwxr-x)  Uid: ( 1000/     tom)   Gid: (  101/systemd-journal)
```

The container is started with `-p` (full docker-compose.yml)

```
version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      - TZ=Europe/Paris
      - USERID=1000
      - GROUPID=1000
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tty: true
    volumes:
      - /storage:/public
    command: '-r -p -s "public;/public;yes;no;yes"'
```

I can reproduce the permission problem with `chmod tom:tom /storage` and restarting the container.
(I remove the `read_only: true` option I was using and still the same behaviour).

Thanks a lot,
Tom
