### ISSUE TITLE
Suddenly can't get container to start

### ISSUE THREAD

**Issue by jeff-h** [dperson/samba#256]
I have had this container running really well for about a year (thanks @dperson for your awesome work), but decided a few days ago to try to get Time Machine working well. It did previously begin a backup, but failed with the macOS error "The network backup disk does not support the required capabilities."

When trying to fix this, I attempted to add a few `-g` options to the container definition in my `docker-compose.yml` (copying those listed [here](https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X)), and rebuilt the container. After this it failed to start back up. The logs show many copies of the following error lines:

````
usermod: no changes
Unable to initialize messaging context!
Unable to initialize messaging context!
Unable to initialize messaging context!
smbd version 4.10.8 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
````

Naturally, I rolled back my changes to my `docker-compose.yml` and have rebuilt the container several times, restarted the server etc but still can't get it back up and running. I've tried everything I can think of, so I am hopeful someone might have a suggestion for me!

**Comment by dperson** [comment]
First you've provided no info on how you're starting it (IE what is in your `docker-compose.yml`), if you have a persistent volume that stores the samba configuration that's generated, or what the options you were setting with `-g` were. Also any other messages that come up while samba is starting may prove useful as well.

**Comment by jeff-h** [comment]
@dperson Really appreciate your time, thanks. Realising I obviously should have copied in my docker-compose.yml, I went through it in detail to sanitise any passwords etc and in doing so noticed the following line, referencing https://github.com/dperson/samba/issues/142:

      - ${DOCKERDIR}/containers/samba/var/lib/samba:/var/lib/samba

Prompted by your comment about persistent volumes, I commented that line out, and it did indeed fix everything. In other words you identified my problem, even with the scant detail I provided. Thanks again!

For reference, my container definition is now:

```
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      TZ: 'Pacific/Auckland'
      USERID: "0"
      GROUPID: "0"
      # Advertise shares:
      NMBD: "true"
      WORKGROUP: "WORKGROUP"
    network_mode: "host"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    # read_only: true
    tmpfs:
      - /tmp
    volumes:
      - /home/jeff:/share/jeff
      - ${EXTERNALDRIVE2}:/share/two

      # See https://github.com/dperson/samba/issues/142
#      - ${DOCKERDIR}/containers/samba/var/lib/samba:/var/lib/samba

      # If changing the name, also change it in avahi's timemachine.service
      - ${EXTERNALDRIVE2}/Backups/TimeMachine:/share/timemachine
    command: '
      -u "jeff;password"
      -u "js;password"
      -u "timemach;password"

      -s "UbuntuHome;/share/jeff;yes;no;no;jeff"
      -s "Two;/share/two;yes;no;no;all"
      -s "Ubuntu Time Machine;/share/timemachine;no;no;no;timemach"
    '
```

The global options from [here](https://wiki.samba.org/index.php/Configure_Samba_to_Work_Better_with_Mac_OS_X) that I am experimenting with, to try to get Time Machine working more stably, are:

```
      -g "fruit:metadata = stream"
      -g "fruit:model = MacSamba"
      -g "fruit:posix_rename = yes"
      -g "fruit:veto_appledouble = no"
      -g "fruit:wipe_intentionally_left_blank_rfork = yes"
      -g "fruit:delete_empty_adfiles = yes"
```
