### ISSUE TITLE
unbound variables ($2 on line 99 and 140)

### ISSUE THREAD

**Issue by wsw70** [dperson/samba#260]
There seems to be a problem when setting variables from a  docker compose file:

```
samba:
    image: dperson/samba
    container_name: samba
    volumes:
      - /:/mount
    ports:
      - "139:139"
      - "445:445"
    environment:
      #- SHARE="data;/data"
      - TZ=Europe/Paris
      #- USER="root;root"
    restart: unless-stopped
```

The configuration above starts (but is probably useless as no shares are defined), with some errors:

```
smbd version 4.10.10 started.
Copyright Andrew Tridgell and the Samba Team 1992-2019
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
open_socket_in(): socket() call failed: Address family not supported by protocol
smbd_open_one_socket: open_socket_in: Address family not supported by protocol
open_socket_in(): socket() call failed: Address family not supported by protocol
smbd_open_one_socket: open_socket_in: Address family not supported by protocol
```

This may be sue to a lack of IPv6 on my server.

But anyway - when trying to set up a share (by uncommenting the variable above), the startup fails with 

    /usr/bin/samba.sh: line 99: $2: unbound variable

It looks like the second parameter (the target directory?) cannot be set. It look slike the offending line is

```
share() { local share="$1" path="$2" browsable="${3:-yes}" ro="${4:-yes}" \
                guest="${5:-yes}" users="${6:-""}" admins="${7:-""}" \
                writelist="${8:-""}" comment="${9:-""}" file=/etc/samba/smb.conf
```

**Comment by dperson** [comment]
Was that a copy and paste from your `docker-compose.yml` that's throwing the errors? The reason that I ask is the most common reason people have gotten this error is using `:` instead of `;`, you have semi-colons above, but I wanted to eliminate that possibility first...

The individual arguments get broken up at the bottom of the script before `share` is called, FYI.

**Comment by wsw70** [comment]
> Was that a copy and paste from your  `docker-compose.yml` that's throwing the errors?

Yes, this is a copy/paste from my `docker-compose.yml`

**Comment by joshkreud** [comment]
Hi, 
I'm getting the same thing on my Raspberry PI.
Maybe it has something to do with the fact, that I have to use Compose 2.1 for VLAN compatibility in other services. 

In my Compose I have
```yaml
 samba:
    image: dperson/samba:armhf
    container_name: samba_main
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - default
    environment:
      TZ: ${TZ}
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - /home/USER:/mnt/adm:z
    command: ${SMB_CMD}
```
and in my .env i have: 
```
SMB_CMD='-u "adm;admpass" -s "admpi;/mnt/adm;yes;no;no;adm"' 
```

If I have it like that, `docker log -f samba` will continuously print `/usr/bin/samba.sh: line 140: $2: unbound variable`
If I switch the `-u` and `-s` command, the error goes to `/usr/bin/samba.sh: line 99: $2: unbound variable`

So I think it definitely has something to do with the argument splitting, because if I do: 
```
SMB_CMD='-s admpi;/mnt/adm;yes;no;no;adm -u adm;admpass' 
```
Note I left out the double quotes. 
Then `docker exec -it samba_main cat /etc/samba/smb.conf` will have the following share section: 

```
 [ admpi]
   path = /mnt/adm
   browsable = yes
   read only = no
   guest ok = no
   veto files = /._*/.apdisk/.AppleDouble/.DS_Store/.TemporaryItems/.Trashes/desktop.ini/ehthumbs.db/Network Trash Folder/Temporary Items/Thumbs.db/
   delete veto files = yes
   valid users = adm -u adm
   admin users = admpass
```
Note the space before the share name and the `valid users`and `admin users`.
And yes I'm definitely using semicolons to split the arguments.
