### ISSUE TITLE
How to access a samba share as root user ?

### ISSUE THREAD

**Issue by janvda** [dperson/samba#279]
I am using the `homeassistant/home-assistant` docker service which is writing the configuration files under folder `/config` as root user.

This `/config` folder is  currently mapped to a docker volume which I would like to access as samba share as "root" user so that I can update the files under the `/config` folder.

I don't want to change the owner or permissions of the files under `/config`.

Is this possible and if so how can this be done ?

**Comment by janvda** [comment]
I have tried following configuration:

```
...
  samba:
    image: dperson/samba
    volumes:
       - 'home-assistant-config:/mount/home-assistant-config'
    ports:
      - "139:139"
      - "445:445"
    environment:
      - USER=root;${SAMBA_ROOT_PASSWORD};0;root;0
      - SHARE=home-assistant;/mount/home-assistant-config;yes;no;no;root;root;;
  home-assistant:
    image: homeassistant/home-assistant:stable
    ports:
      - 8123:8123
    privileged: true
    volumes:
       - home-assistant-config:/config
...
```
