### ISSUE TITLE
Unable to discover and unable to write

### ISSUE THREAD

**Issue by HouCoder** [dperson/samba#283]
Hi, I'm having a little trouble on the docker-compose integration, I can't find my share on macOS's Finder app, but I can connect the share via Finder -> Go -> Connect to Server by manually typing the share's IP address and hit connect, but after typing username and password the connected volume is read-only to me.

 here is my docker-compose file:

```yml
version: '3'

services:
  samba:
    image: dperson/samba:aarch64
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: always
    volumes:
      - /mnt/hdd:/data
    command: >
      -s "data;/data;yes;no;no;tim;none;;COMMENT"
      -u "tim;tim_password"

networks:
  default:
```

Did I miss something? thanks.

**Comment by HouCoder** [comment]
Fixed the data-write issue by putting `tim` into admin list `"data;/hdd;yes;no;no;;tim;;COMMENT"`, this is weird to me as this share is not read-only and `tim` was in `users` list.

**Comment by matttan90** [comment]
Use the `nmbd` option, and you should be able to see it on the Finder app.

```
-n          Start the 'nmbd' daemon to advertise the shares
```

**Comment by Paul-Ver** [comment]
I had a similar issue regarding not showing up in MacOS, key here is to combine the info in readme and in the wiki.

Be sure to:
- expose the 137 and 138 UDP ports
- use "network_mode: host"
- set environment "NMBD: "true""

```
version: '3'
services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      TZ: 'Europe/Amsterdam'
      WORKGROUP: "WORKGROUP"
      NMBD: "true"
      RECYCLE: ""
      USERID: "1001"
      GROUPID: "1001"
    command: '-s "sharename;/folderindocker/"'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    volumes:
      - /FOLDER/ON/HOST/MACHINE/:/folderindocker
```

The folder in my example isn't writeable (due to how it's configured); but it may also be worth to set: "read_only: false" in your case.
