### ISSUE TITLE
Need help on docker-compose usage

### ISSUE THREAD

**Issue by cvladan** [dperson/samba#3]
I tried every possible way to start container from docker-compose, but without a way to configure it immediatly in `docker-compose.yml`. Can you give me some exampleif I want to share publicly two folders:

```
myname:
  image: dperson/samba
  volumes_from:
   - storage
  # command: -s "db;/var/lib/mysql" -s "www;/var/www" -s "data;/data"
  # entrypoint: ["samba.sh", '-s "data;/data"'] ???
  ports:
   - 139:139
   - 445:445
```

Help, please.
I just want to type `docker-compose up -d`, but cannot make it work.
