### ISSUE TITLE
Hide folders which are not accessible for a user

### ISSUE THREAD

**Issue by kubek93** [dperson/samba#302]
I don't know why guests users can see folder from `SHARE2` variable which should be reached out only for user `kube_k`. I suppose these suggestions should help in this case: `https: // serverfault.com / questions / 144339 / hiding-samba-share-from-browse-list-for-unauthorised-users` but I cannot find how to set up` hide unreadable = yes` in `docker-compose` file.

My configuration:
```
samba:
        image: dperson/samba:latest
        container_name: samba-dperson
        restart: always
        volumes:
            - ./storage/samba/anonymous:/samba/anonymous
            - ./storage/samba/admin:/samba/admin
        environment:
            USER1: 'kube_k;admin'
            SHARE1: 'public;/samba/anonymous'
            SHARE2: 'admin;/samba/admin;yes;no;no;kube_k'
        ports:
            - "139:139"
            - "445:445"
```
Generated smb.conf:
```
[admin]
   path = /samba/admin
   browsable = yes
   read only = no
   guest ok = no
   veto files = /.apdisk/.DS_Store/.TemporaryItems/.Trashes/desktop.ini/ehthumbs.db/Network Trash Folder/Temporary Items/Thumbs.db/
   delete veto files = yes
   valid users = kube_k

[public]
   path = /samba/anonymous
   browsable = yes
   read only = yes
   guest ok = yes
   veto files = /.apdisk/.DS_Store/.TemporaryItems/.Trashes/desktop.ini/ehthumbs.db/Network Trash Folder/Temporary Items/Thumbs.db/
   delete veto files = yes
```
Do you have any ideas how to solve that?
