### ISSUE TITLE
Users cannot delete their own files

### ISSUE THREAD

**Issue by kaixuan-dev** [dperson/samba#310]
### Users cannot delete their own files
Hi,
I try to run this image(dperson/samba:armhf) on my Raspberry PI 4. Everything is fine except that user can't delete their files(user can create new file). 
I found that if I update line 100 of the samba.sh to 'sed -i '/recycle/d; /vfs/d' $file' , i can delete my files.  like this
```
### recycle: disable recycle bin
# Arguments:
#   none)
# Return: result
recycle() { local file=/etc/samba/smb.conf
    #sed -i '/recycle:/d; /vfs objects/s/ recycle / /' $file
    sed -i '/recycle/d; /vfs/d' $file
}
```
#### How to reproduce this bug

- docker pull dperson/samba:latest
- Mount a U-disk whose file system is **exFAT**(ext4 is ok)
- Start docker container

**Comment by dperson** [comment]
Using a weird MS filesystem that can't store normal POSIX metadata isn't supported by upstream samba, so it definitely isn't something that the container supports.

**Comment by user9823749** [comment]
I have exactly same problem with deleting files on exfat filesystem i cant change it to ext4 dont have other hdd.

Can you tell me please how access samba.sh to modify it? Nano is not working apt-get too.

Thank you

**Comment by kaixuan-dev** [comment]
if u have same problem 
First u need to remove  dperson/samba:armhf on your device
```
docker rmi -f dperson/samba:armhf 
````
Second step: Please clone this project and modify samba.sh , I update line 100 of the samba.sh to 'sed -i '/recycle/d; /vfs/d' $file' 
```
### recycle: disable recycle bin
# Arguments:
#   none)
# Return: result
recycle() { local file=/etc/samba/smb.conf
    #sed -i '/recycle:/d; /vfs objects/s/ recycle / /' $file     
    sed -i '/recycle/d; /vfs/d' $file
}
```
then build a new docker image, I did this on raspberry pi so i remove line 2 of Dockerfile.armhf 
```
FROM arm32v6/alpine
#COPY qemu-arm-static /usr/bin/
MAINTAINER David Personette <dperson@gmail.com>
```
Finally, i build a new image by this command
```
docker build -f Dockerfile.armhf -t dperson/samba:armhf .
```

**Comment by user9823749** [comment]
Thank you its working! :P

**Comment by user9823749** [comment]
Do you know better way to share exfat drive over network? I still have problems with moving files i got many errors not in all files but on some of them i dont know why i cant move them or delete all files have root privileges. Im using raspberry pi4

**Comment by kaixuan-dev** [comment]
Maybe you can use FTP or SFTP，if u stil want to use samba  try to install it on you raspberry pi.
by the way, you can try to build a image and see log of container.
here is all  my scripts:
/etc/rc.local
```
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

/home/pi/script/run.sh

exit 0
```

/home/pi/script/run.sh
```
#!/bin/sh
sudo mount -o uid=pi,gid=pi  /dev/sda1 /media/mount
```

docker-compose.yml
```
version: '3.4'
services:
  samba:
    container_name: server-samba
    image: dperson/samba:armhf
    restart: unless-stopped
    ports:
      - '445:445'
      - '139:139'
    volumes:
      - '/media/mount/samba:/mount'
    command:
      -u 'name;password'
      -s 'dir;/mount;no;no;no;name'
      -r
      
networks:
  default:
```
