### ISSUE TITLE
Get write access without using option -p

### ISSUE THREAD

**Issue by janvda** [dperson/samba#312]
I know that it is possible to get write access to samba share using option `-p`.

The problem is that this option changes the ownership of this folder and all its files on the host to the smbuser.

This is not acceptable in my case as those files are also read and updated by another container application.

So is there a way to have write access to a samba share without using option '-p' or changing the ownership of the folder and its files ?

**Comment by janvda** [comment]
I managed to get it working by:

1.  adding the `smbuser` to the unix group id that is set for the shared folder and its files.
    E.g. the following command did the job:  (1000 is the typically the group id of the default user that is created by most docker engines).

```
usermod -a -G 1000 smbuser
```

The following command can be used to list all the groups where the user `smbuser` belongs to:

````
groups smbuser
````

2.  Assure that the samba user (the user you use to logon to the samba share) is specified in the writelist of your docker command (see under option `-s`).

This might seem obvious but the readme is a bit confusing as it seems to indicate that the writelist only needs to be set when using a **read-only** share.

![image](https://user-images.githubusercontent.com/17238398/82754614-526e3700-9dce-11ea-8351-18189f18ed2e.png)

So here below a working example of my samba configuration in the docker-compose file:

```
 samba:
    image: dperson/samba
    volumes:
      ...
       - 'node-red4-data:/mount/node-red4-data'
    ports:
      - "139:139"
      - "445:445"
    environment:
    ...
      - USER3=${SAMBA_USER};${SAMBA_PASSWORD}
      - SHARE3=node-red4;/mount/node-red4-data;yes;no;no;${SAMBA_USER};;${SAMBA_USER};
```

**Comment by janvda** [comment]
Maybe it is possible to achieve this also by setting the environment variables `GROUPID` or even only `USERID`

![image](https://user-images.githubusercontent.com/17238398/82755111-daa20b80-9dd1-11ea-8898-a24cc0095225.png)

**Comment by Mailblocker** [comment]
Hi, 
I stumbled on the same/identical problem, this one is docker nextcloud related but anyways:
My task was to have a samba docker container running to be able to scan into a network folder directly from my printer. At the same time I wanted to have access from my nextcloud docker container to this folder to access the documents and **delete** them when no more needed. So I needed write access from another container.

I succeded with this docker-compose setup:
```
nextcloud:
    ...
    volumes:
      - .scans:/mnt/scans:rw
    ...

samba:
    image: dperson/samba
    container_name: samba
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    restart: always
    volumes:
      - ./scans:/mnt/scans:rw
    environment:
      - USERID=33
      - GROUPID=33
      - PERMISSIONS=true
      - TZ='Europe/Berlin'
      - SMB=true
      - USER1=scans_user;scans_pw
      - SHARE1=scans;/mnt/scans;yes;no;no;scans_user;;;
```

Without setting PERMISSIONS the folder scan is created with the ower root and no access is possible, either from my printer nor from the nextcloud.

Maybe this post helps someone, it took me hours to find this solution (https://github.com/nextcloud/docker/issues/229) regarding the needed user ID and SMB which is needed for my HP printer.

**Comment by janvda** [comment]
... but is `PERMISSIONS=true` not same as option `-p` which will change the owner of the shared folder and its files which is just the thing I didn't want ?

**Comment by Mailblocker** [comment]
Yes, PERMISSIONS is the same option as -p. But, at least in my case, with the flag/option set I can delete those files from the other container.

**Comment by janvda** [comment]
I am using named volumes in my docker compose file something like this:

```
version: "3.7"
volumes:
   ...
    node-red4-data:
services:
 node-red4:
    build: node-red4
    #privileged: true
    volumes:
       - 'node-red4-data:/data'
    ports:
      - "1885:1880"
     ...
 samba:
    image: dperson/samba
    volumes:
      ...
       - 'node-red4-data:/mount/node-red4-data'
    ports:
      - "139:139"
      - "445:445"
    environment:
    ...
      - USER3=${SAMBA_USER};${SAMBA_PASSWORD}
      - SHARE3=node-red4;/mount/node-red4-data;yes;no;no;${SAMBA_USER};;
```

This named volumes is writeable by my node-red4 docker service.  So there I didn't have any need to update the ownership of this folder and its files.
