### ISSUE TITLE
set_variable_helper(yes = lanman auth=yes): value is not boolean

### ISSUE THREAD

**Issue by YarmoM** [dperson/samba#321]
I have just updated the docker container and it now fails to start. Logs:

```
smbd version 4.12.2 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
set_variable_helper(yes = lanman auth=yes): value is not boolean!
error opening config file '/etc/samba/smb.conf'
```

I tried removing certain environment variables but no matter the changes, this error remains. I couldn't find related changes in the documentation.

My config which has been working up until today:

```
  smb:
    image: dperson/samba
    command: |-
      -p
      -S
      -s Docs;/mnt/documents;yes;no;no;all;none
      -u username;password
      -g "security = user"
      -g "ntlm auth=yes"
      -g "lanman auth=yes"
    volumes:
      - ./documents:/mnt/documents
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    environment:
      - TZ=Europe/Amsterdam
      - NMDB=true
      - WORKGROUP=workgroup
      - USERID=1000
      - GROUPID=1000
    labels:
      - "traefik.enable=false"
```

Do you have any idea what could cause this?
