### ISSUE TITLE
Can mount but no write permissions

### ISSUE THREAD

**Issue by MrksHfmn** [dperson/samba#334]
thanks a lot for the docker image! so far it works really well, unfortunately i can't write with my user. the write permissions on the host system are correct. i tried to set the uids and gids in the compose file.

```
version: '3.8'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - TZ="Europe/Berlin"
    networks:
      - samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    volumes:
      - /mnt/storage/users/markus:/mnt/users/markus/
    command: >
      -w "WORKGROUP"
      -s "Markus Daten;/mnt/users/markus;yes;no;no;markus"
      -u "markus;Test123;1000;markus;1000"

networks:
  samba:
    external: true
```

**Host system**: 

```
root@HOME-SERVER:[users]> ls -la /mnt/storage/users/
drwxr-xr-x 5 markus markus 4,0K 2020-09-01, 14:58:13   markus/

root@HOME-SERVER:[users]> id markus
uid=1000(markus) gid=1000(markus) groups=1000(markus),976(docker),991(lp)

```

**Comment by mainto** [comment]
try USERID and GROUPID environments instead "1000;markus;1000" on command.
I had same issue but I resolved with it.

**Comment by Melzmann** [comment]
``` yaml
version: '3.8'

services:
  samba:
    image: dperson/samba
    environment:
      - TZ="Europe/Berlin"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    volumes:
      - /home/user:/home/user
    command: >
        -u "user;pass;1000;user;1000"
        -s "user private share;/home/user;yes;no;no;user"
        -p
```

Works for me.
I think you should add the "-p" flag in command.
