### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by lukasPF** [dperson/samba#344]
Hello,
I wanted to creat 5 Folders one is public, everybody can see it but only estimated users can write to it, and 4 Folders with one user per folder who can write things that nobody else can see. public shares work but I can't login to the different private Folders

This is my docker compose file
```

version: '3.3'

services:
  samba:
    image: dperson/samba:latest
    command: >
      -u "lukas;badpass"
      -u "peter;badpass"
      -u "johanna;badpass"
      -u "sabine;badpass"
      -u "pi;12345678"
      -s "Public;/shares/public;;;;;pi;lukas,peter,johanna,sabine"
      -s "Lukas;/shares/lukas;;no;;lukas;pi;lukas"
      -s "Peter;/shares/peter;;no;;peter"
      -s "Sabine;/shares/sabine;;no;;sabine"
      -s "Johanna;/shares/johanna;;no;;johanna"
    volumes:
      - /mnt/public:/shares/public
      - /mnt/lukas:/shares/lukas
      - /mnt/sabine:/shares/sabine
      - /mnt/peter:/sahres/peter
      - /mnt/johanna:/shares/johanna
    environment:
      - USERID=1000
      - GROUPID=1000
    network_mode: host
    ports:
      - "139:139"
      - "445:445"
    restart: unless-stopped

```

**Comment by RezzZ** [comment]
i've got the same issue, only if you define a specific admin you can write into the shares...
I'm trying a different branch which seem to work better. it looks like this project is not much alive any more.

This one is working for me:
```
  samba:
    container_name: samba
#    image: dperson/samba:latest
    image: m4rc77/samba:latest
    environment:
      - GLOBAL=client min protocol = NT1
      - GLOBAL2=ntlm auth = ntlmv1-permitted
      - GLOBAL3=force user =
      - GLOBAL4=force group =
      - TZ=Europe/Amsterdam
      - USER=user;password1
      - USER2=user2;password2
      - USER3=sonos;sonos
      - SHARE=music;/mnt/music;yes;yes;no;all;user1,user2;;music share
      - PERMISSIONS=true
      - SMB=true
    ports:
      - 139:139
      - 445:445
    restart: unless-stopped
    volumes:
      - /mnt/2tb_drive/music:/mnt/music
```
