### ISSUE TITLE
HealthCheck issue with anonymous account disabled

### ISSUE THREAD

**Issue by Mr-DeWitt** [dperson/samba#345]
Hi!

I had to disabled the anonymous login, for security purpose. 

I use the following `command` param in docker-compose:

```
command: |
    .....users_and_shares_.....
    -g "restrict anonymous = 2"
```

The container works perfectly: I can connect, download and upload files. But the `healthcheck` status is at **`unhealthy`**. The reason is: **tree connect failed: NT_STATUS_ACCESS_DENIED**.
I checked the image's health check function and I found this: `HEALTHCHECK &{["CMD-SHELL" "smbclient -L \\\\localhost -U % -m SMB3"] "1m0s" "15s" "0s" '\x00'}`. So it tries to authenticate anonymously I suppose.

Can an authenticated health check be implemented, please?

Regards,
Szilard

**Comment by mhbates** [comment]
I just did this as well and seem to have the same issue.

**Comment by ndm13** [comment]
Same issue here using Docker Compose.  Connection works perfectly but container health check shows as unhealthy.
```yml
version: '2.0'
services:
  samba:
    image: dperson/samba
    container_name: samba
    ports:
     - 139:139
     - 445:445
    environment:
     - USER=samba;$PASSWORD
     - SHARE=share;/mounted_volume;yes;no;no;samba;samba;samba;
     - USERID=1000
     - GROUPID=1000
    volumes:
     - /folder/on/host:/mounted_volume:rw
```
