### ISSUE TITLE
GROUPID env take what effect?

### ISSUE THREAD

**Issue by liuhuiping2013** [dperson/samba#352]
i've set USERID=1001 GROUPID=1001, and use win10 client to create file, but file owner is 0:1001 (uid:gid).
later, i use centos client to create file, file owner also is 0:1001 (uid:gid).
so, what does USERID GROUPID do?

docker-compose.yml here:
```
services:
  samba:
    image: dperson/samba
    environment:
      USERID: 1001
      GROUPID: 1001
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/max/smb:/mnt:z
    command:
      - -s
      - "Mount;/mnt;yes;no;no;max;max"
      - -u
      - "max;max"
```
