### ISSUE TITLE
Can no longer connect to share with latest dockerhub armhf image - Access denied

### ISSUE THREAD

**Issue by steveoleary** [dperson/samba#356]
Hi,

as of today i've been unable to connect to the samba share set up on my Raspberry Pi. I noticed that there's a recent update of this image on Dockerhub, so am wondering if that has possibly introduced the problem as I have Watchtower set up. Also Portainer shows the Container state as 'Unhealthy'. The logs don't report any problems, when trying to access the share both my Macs now report 'Access to your account on the server 192.168.x.x denied'. 

I've looked for the previous image digest id or tag but have had no luck, so it's possible the version update is not the culprit, but it's the only clue I have at the moment. If I figure out the cause I'll return here to update and close the issue

**Comment by solideus** [comment]
Me too.

I pulled image: dperson/samba:rpi and works fine. With dperson/samba not works

Raspberry pi 4 docker 20.10.2

**Comment by tlux** [comment]
For me, it doesn't work either. 
Neither `dperson/samba` nor `dperson/samba:rpi` does. 
And the `rpi` tagged image also seems to be very old.

This is my docker-compose.yml:

```yaml
services:
  samba:
    container_name: samba
    image: dperson/samba
    environment:
      - TZ=Europe/Berlin
      - USERID=1000
      - GROUPID=1000
    ports:
      - '139:139'
      - '445:445'
    restart: unless-stopped
    volumes:
      - '/media/data:/data:z'
    command: >
      -w "WORKGROUP"
      -s "data;/data;yes;no;no;foo"
      -u "foo;bar"
      -p
```

**Comment by eumaios** [comment]
same here. Access denied from Mac to odroid xu4 with Dockstarter. It worked ok before.

**Comment by cherjr** [comment]
> Me too.
> 
> I pulled image: dperson/samba:rpi and works fine. With dperson/samba not works
> 
> Raspberry pi 4 docker 20.10.2

this one indeed works fine for me - but only with no min server protocol specified.
(RaspbianOS pi4)

**Comment by mariusherta** [comment]
I have the same issue on my 4GB Raspberry Pi 4. Additionally the container appears unhealthy in Portainer and uses more CPU than usual (~30% as compared to the usual max 5% )

**Comment by hpkfq** [comment]
Same here. Rapberry Pi 4. The container is unhealthy not working after recent update. It shows "Last output | do_connect: Connection to localhost failed (Error NT_STATUS_IO_TIMEOUT)" in Portainer.

**Comment by JamieWhite** [comment]
I've got a work around for this. Im not a Docker expert so open to feedback on a better way of doing this 😄 

If you still have the old image in docker you you can find it's sha256 number with `docker images | grep samba`  which for me returned

```
dperson/samba                  latest    a3708e557f69   2 days ago     53.2MB
dperson/samba                  <none>    d036f2b75b12   4 weeks ago    49.3MB
```

The 4 weeks ago version is what I want to use.

I couldn't figure out how to get my `docker-compose.yml` to reference it by sha256 but I did manage to tag my own version off that 4 week old version with: `docker tag d036f2b75b12 jamie/samba` then I used `jamie/samba` in my docker-compose.yml. Doing a `docker-compose pull` spat out an error saying the repo doesn't exist but when I did `docker-compose up` it used my image and started working again

**Comment by steveoleary** [comment]
@JamieWhite thanks that's good to know, unfortunately I don't have the old image, I've tried running `docker pull dperson/samba@sha256:d036f2b75b12` but get an invalid reference format error. Do you perhaps have access to the full sha256 digest id, the shortened one appears not to work with docker pull?

**Comment by ejsmit** [comment]
I managed to get mine working by editing the dockerfile to change the alpine version to a previous release and rebuilding the image.  Apparently it is related to a docker issue around return values from system calls and the latest c library updates.  The older alpine base images contain a older c library and does not cause problems.

**Comment by quentinb69** [comment]
If you want, until a correction is applied on this repo, I pushed the working container for raspberry pi on raspbian buster on my dockerhub (you can check the hash to be sure it has not been modified/corrupted) : **quentinb69/samba:dperson**

*Note: I will probably never update this image so you will not be up to date using it*

**Comment by ArtJames** [comment]
Fix for Raspi-OS 32bit:

wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.4-1~bpo10+1_armhf.deb
sudo dpkg -i libseccomp2_2.4.4-1~bpo10+1_armhf.deb

Explanation:
https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal-and-alpine-3-13

Install package, restart docker or reboot system, and samba works again with the latest docker image.

**Comment by vonProteus** [comment]
back port of libseccomp2 didn't helped me

**Comment by aventustudio** [comment]
> 
> 
> Fix for Raspi-OS 32bit:
> 
> wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.4-1~bpo10+1_armhf.deb
> sudo dpkg -i libseccomp2_2.4.4-1~bpo10+1_armhf.deb
> 
> Explanation:
> https://docs.linuxserver.io/faq#my-host-is-incompatible-with-images-based-on-ubuntu-focal-and-alpine-3-13
> 
> Install package, restart docker or reboot system, and samba works again with the latest docker image.

Thank you very much for sharing, it worked for me!
Here is my config:
```
version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      - TZ=Europe/Berlin
      - USERID=1000
      - GROUPID=1000
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - '/mnt/ssd:/mnt/ssd:z'
    command: >
      -w "WORKGROUP"
      -u "${ENV_USER};${ENV_PASS}"
      -s "RPISSD;/mnt/ssd;yes;no;no;pi"
      -r
      -p

networks:
  default:
```
