### ISSUE TITLE
Setup not creating character mappings

### ISSUE THREAD

**Issue by Bulmanator** [dperson/samba#357]
I have this setup with docker-compose and my file is as such:
```
    samba:
        container_name: samba
        image: dperson/samba
        networks:
            - default
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139/tcp"
            - "445:445/tcp"
        environment:
            - TZ=${TZ}
        volumes:
            - "/mnt/mount_point:/mnt/mount_point:z"
        tmpfs:
            - /tmp
        read_only: true
        stdin_open: true
        tty: true
        restart: unless-stopped
        command: >-
            -w 'WORKGROUP'
            -c '0x3a:0xb7'
            -r
            -u 'user;${SMB_PASSWORD};1000;1000'
            -s 'share;/mnt/mount_point;yes;no;no;user'
```
However the character mapping (colon to midpoint) isn't added to the configuration. 

When executing a shell into the running container and looking at the contents of `smb.conf` it does add the `vfs objects = catia fruit streams_xattr` values but there is no `catia:mappings` line which should've been generated by the `charmap` function in `samba.sh` upon startup.
