### ISSUE TITLE
[Need Advice] SMB share for Windows 10 without guest usage

### ISSUE THREAD

**Issue by cybermcm** [dperson/samba#359]
I'm using the current docker image for ARM (Raspberry).

Everything works, but I'm not able to access my SMB shares with my work notebook (current Win 10, no admin rights).
I can't connect because of
```
net use \\nas
System error 1272 has occurred.
You can't access this shared folder because your organization's security policies block unauthenticated guest access. These policies help protect your PC from unsafe or malicious devices on the network.
```
To get past this I can set
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LanmanWorkstation\Parameters\AllowInsecureGuestAuth to 1 and then it works but I can't set this setting on my work notebook (no admin rights).
Every share is set without guest access.

```
samba:
  # <name;/path>[;browse;readonly;guest;users;admins;writelist;comment]
  container_name: samba
  environment:
   - NMBD=true
   #- PERMISSIONS=true
   - USER=xxx;yyy
   - USERID=0
   - GROUPID=0
   - WORKGROUP=xxx
   - RECYCLE=true
   - SHARE1=data;/mount/usb1;yes;no;no
   - SHARE2=docker;/mount/docker;yes;no;no
   - SHARE3=data2;/mount/usb2;yes;no;no
   - SHARE4=archive;/mount/usb1/archive;yes;no;no
   - SHARE5=mp3;/mount/usb1/media/mp3;yes;yes;no
   - SHARE6=tv;/mount/usb1/media/tv;yes;yes;no
   - SHARE7=kids;/mount/usb1/media/kids;yes;yes;no
  image: dperson/samba
  labels:
   - com.centurylinklabs.watchtower.enable=true
  network_mode: host
  ports:
   - "137:137/udp" # required to advertise shares (NMBD)
   - "138:138/udp" # required to advertise shares (NMBD)
   - 139:139
   - 445:445
  restart: always
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /etc/localtime:/etc/localtime:ro
   - /mnt/usb1:/mount/usb1
   - /mnt/usb2:/mount/usb2
   - /opt/docker:/mount/docker
```
It seems that the initial connection is still anonymous. Am I missing something?
