### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by zhejunliux** [dperson/samba#365]
hi, dperson boss:
# server:104.193.88.77/24
```
user root
mkdir -p /home/ai-eng
chmod -R 666 /home/ai-eng
docker run -it --name samt -p 139:139 -p 445:445 -v /home/ai-eng/:/home/ai-eng/ -d dperson/samba -p -s "app;/home/ai-eng/;yes;no;yes;"
ls ~/tmp
kk.txt   nn.txt
cp -r ~/tmp /home/ai-eng
```
# client:104.193.88.76/24
```
user nj
smb://104.193.88.77/
vim tmp/kk.txt
type kkkk
```
**error_info:You do not have sufficient permissions to write to the file**

# to solve
```
ssh root@104.193.88.77
docker restart samt
action
ssh nj@104.193.88.76
smb://104.193.88.77/
vim tmp/kk.txt
type kkkk
no error
```
# tell me why? and  right solution, tks.

**Comment by ciB89** [comment]
same issue as in #364

**Comment by leqii-com** [comment]
我是加了一个用户，提示拒绝访问，貌似只能用宿主主机已创建的用户，自己-u创建的用户 就拒绝访问，不知道为何？大师你知道吗？
```
version: '3'
services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    volumes:
      - /data/web/files:/mount
    environment:
      TZ: Asia/Shanghai
    command:
        - '-u'
        - "smb;mima"
        - "-s"
        - "share;/mount;yes;no;no;smb;smb;smb;"
```

**Comment by zhejunliux** [comment]
希望对你有帮助bro

```
version: '3'
services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    volumes:
      - /data/web/files:/mount
    environment:
      TZ: Asia/Shanghai
    command:
        - '-u'
        - "smbx;mima"
        - "-s"
        - "share;/mount;yes;no;no;smbx;smbx;smbx;"
```
