### ISSUE TITLE
NT_STATUS_INVALID_LOGON_HOURS and no date set in container

### ISSUE THREAD

**Issue by sbruhse** [dperson/samba#374]
Hello!
When I am sending a file via my printer (pretty old smb client) I am getting following error message:
```
usermod: no changes
usermod: no changes
addgroup: gid '1000' in use
No builtin backend found, trying to load plugin
smbd version 4.13.7 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_DMALLOC_MARK and LOG_CHANGED
Processing section "[mount]"
added interface eth0 ip=172.24.0.2 bcast=172.24.255.255 netmask=255.255.0.0
INFO: Profiling support unavailable in this build.
Registered MSG_REQ_POOL_USAGE
No builtin backend found, trying to load plugin
Registered MSG_REQ_POOL_USAGE
Registered MSG_REQ_POOL_USAGE
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
waiting for connections
Registered MSG_REQ_POOL_USAGE
setup_new_vc_session: New VC == 0, if NT4.x compatible we would close all old resources.
setup_new_vc_session: New VC == 0, if NT4.x compatible we would close all old resources.
logon_hours_ok: failed to get gmtime. Failing logon for user scanner
check_ntlm_password:  Authentication for user [scanner] -> [scanner] FAILED with error NT_STATUS_INVALID_LOGON_HOURS, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 112 (4.13.7)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 112): Signal 11: Segmentation fault in 4.13.7
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
Could not find child 87 -- ignoring
Registered MSG_REQ_POOL_USAGE
setup_new_vc_session: New VC == 0, if NT4.x compatible we would close all old resources.
setup_new_vc_session: New VC == 0, if NT4.x compatible we would close all old resources.
logon_hours_ok: failed to get gmtime. Failing logon for user scanner
check_ntlm_password:  Authentication for user [scanner] -> [scanner] FAILED with error NT_STATUS_INVALID_LOGON_HOURS, authoritative=1
===============================================================
INTERNAL ERROR: Signal 11: Segmentation fault in pid 113 (4.13.7)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 113): Signal 11: Segmentation fault in 4.13.7
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
```

When I execute a "date" on the container I get back the following: `Sun Jan  0 00:100:4174038  1900`

The docker-compose.yml is the following:
```
  samba:
    image: dperson/samba
    restart: always
    ports:
     - "139:139"
     - "445:445"
    volumes:
     - ./incoming:/mount
    command: samba.sh -u "scanner;password;1000;user;1000" -s "mount;/mount;no;no;no;scanner" -w "mayan" -g "log level = 2" -S -p
    environment:
      USERID: 1000
      GLOBAL: 'client min protocol = NT1'
      GLOBAL2: 'ntlm auth = ntlmv1-permitted'

```

The installation was working once. Since I made a docker-compose pull I discovered that issue. I am running the container on an rpi, so the arm image is been taken.

I hope you can help me.

Greetings
Simon
