### ISSUE TITLE
Yet another permission issue submission

### ISSUE THREAD

**Issue by Pingu-Pox** [dperson/samba#380]
I feel like I've scraped all the suggestions from the open/closed issues regarding lack of read/write permissions when accessing your samba share (in my case, and most other cases Windows 10)

I know the share is pointed properly as I can browse it's contents with guest mode turned on, but as soon as I turn guest mode off and try to configure the share for my user, I get an error saying the share is not accessible (I can see the share, can't view contents).

Here's my docker-compose.yml, it looks basically the same as everyone else's.

```
samba:
    container_name: samba
    image: dperson/samba
    volumes:
      - my-volume:/content:z
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    restart: unless-stopped
    command: >
        -u "user;pass;1000;user;1000"
        -s "content;/content;yes;no;no;user"
        -p
volumes:
  my-volume:
```

I've tried these at the end of my command block:
-g "force user =" -g "force group ="
-p

I've tried these as environment variables:
(the ids of my base image user running in ubuntu)
SHARE: "content;/content;yes;no;no;user"
USERID: 1000
GROUPID: 1000 
PERMISSIONS:

I've tried with environment variables (SHARE, USER, USERID, GROUPID), or with the above command block. I open the container with bash and ls -l tells me that /content is owned by smbuser smb. Is user;pass;1000;user;1000 passed into smbuser and smb somehow? Shouldn't the share be owned by the user I defined?

Docker logs samba shows me the following:
Added user user.
smbd version 4.12.2 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections

So it is successfully creating my user, but when I try to auth as said user in Windows to the SMB share, I get errored that the share is not accessible.

(Edit:)
Figured I'd add more info as I have trouble sitting still:
my-volume is owned by root root when inspecting it from the base os (ubuntu)
my-volume is owned by smbuser smb when inspecting it from inside the samba container.
I cannot connect to the samba share from another ubuntu server using smbclient, here's what I get:

```
root@other-host:~$ /usr/bin/smbclient -L local IP of samba server
WARNING: The "syslog" option is deprecated
Enter WORKGROUP\root's password: <I entered the password>

        Sharename       Type      Comment
        ---------       ----      -------
        wikicontent     Disk
        IPC$            IPC       IPC Service (Samba Server)
Reconnecting with SMB1 for workgroup listing.
protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE
Failed to connect with SMB1 -- no workgroup available
root@other-host:~$
```

So I added the -w "WORKGROUP" command to the above docker-compose.yml's command block, but that didn't change anything when trying to connect from W10 or Ubuntu.
