### ISSUE TITLE
can't move files one on the other

### ISSUE THREAD

**Issue by mg64ve** [dperson/samba#395]
Hello I have the following docker-compose.yml:

```
version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'Europe/Rome'
      USERID: 1000
      GROUPID: 1000
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /R1B/share/tmp:/data/share/tmp:z
      - /R1B/share/backup:/data/share/backup:z
      - /R1B/share/files:/data/share/files:z
    command: '-s "tmp;/data/share/tmp;yes;no;no;${SAMBA_USER}" -s "backup;/data/share/backup;yes;no;no;${SAMBA_USER}" 
                -s "downloads;/data/share/files;yes;no;no;${SAMBA_USER}" -u "${SAMBA_USER};${SAMBA_PASSWORD}" -p -w MGNET'

networks:
  default:
```

SAMBA_USER and SAMBA_PASSWORD are in .env file.

The following operations fail:

```
>touch tt
>touch pp
>mv pp tt
mv: cannot move 'pp' to 'tt': Input/output error
```

Any good idea?
