### ISSUE TITLE
Need SMB 1 for old printer access

### ISSUE THREAD

**Issue by Maximus48p** [dperson/samba#403]
I have an old multi printer/scanner which can only network using SMB 1. 
Is SMB 1 still supported? Or do i need to download an older version?

Thanks in advanced!

**Comment by ErikPrantare** [comment]
Try changing the minimum protocols in /etc/samba/smb.conf to NT1. This is a dialect of SMB1, and works with my ps2 which also needs SMB1.

**Comment by rsun-thoughtworks** [comment]
> I have an old multi printer/scanner which can only network using SMB 1. Is SMB 1 still supported? Or do i need to download an older version?
> 
> Thanks in advanced!

What is your approach?

If docker-compose, try this

```
version: '3.0'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'EST5EDT'
    network_mode: "host"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/download/movies:/samba/public/seagate3t
    command: '-n -S -s "share;/mnt;yes;no;yes;all;" -p'
```

This capital `-S` is for set SMB1 as minimum version.

```
-S          Disable SMB2 minimum version
```

Hope this helps.
