### ISSUE TITLE
QNAP: read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.

### ISSUE THREAD

**Issue by Maximus48p** [dperson/samba#404]
From my scanner i want to scan directly to my Qnap NAS, but my NAS doesn't support SMB1 anymore. 
My printer/scanner only support SMB1 to write to.

I'm using Docker-compose file:

```
  samba:
    image: dperson/samba
    container_name: Samba-x
    hostname: samba-scan
    restart: always
    networks:
      qnet-static-eth1-79e6cc:
        ipv4_address: 192.168.1.41
    ports:
       - 139:139
       - 445:445
    stdin_open: true
    tmpfs:
      - /tmp
    tty: true
    environment:
      - TZ=Europe/Amsterdam
      - USER=printer;printer
      - RECYCLE=false
      - SHARE=printerscan;/mnt/scan;yes;no;yes;all
      - SHARE2=ocr-pickup;/mnt/ocr;yes;no;yes;all
      - SMB=1
      - USERID=1001 # user 'printer' on QNAP NAS
      - GROUPID=100 # group everybody
    volumes:
      - /share/scanned_originals/printerscan:/mnt/scan
      - /share/scanned_originals/OCR-pickup:/mnt/ocr
    command: >-
      -S
      -g "server min protocol = NT1"
```

And getting this error:
```
usermod: no changes
smbd version 4.12.2 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
===============================================================
INTERNAL ERROR: Signal 11 in pid 95 (4.12.2)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 95): internal error
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
===============================================================
INTERNAL ERROR: Signal 11 in pid 96 (4.12.2)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 96): internal error
unable to produce a stack trace on this platform
dumping core in /var/log/samba/cores/smbd
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
read_fd_with_timeout failed for client 192.168.1.10 read error = NT_STATUS_END_OF_FILE.
etc.
```
QNAP NAS IP = 192.168.1.10

When connecting from my MacBook i'm getting the Panic INTERNAL ERROR. Although i'm getting this error, Im able to connect using both IP addresses; 192.168.1.10 and 192.168.1.41. The folders are reachable and writable.

And when i try to connect from my scanner/printer as folder location it won't connect at all.
My printer/scanner only supports SMB 1.
On my Qnap i made an extra user 'printer' and granted this user RW right to the shared folder (and subfolders): /share/scanned_originals

What am i doing wrong? 
Any help is very much appreciated.

Thank you.
Marnix
