### ISSUE TITLE
canonicalize_connect_path failed for service

### ISSUE THREAD

**Issue by mouzzampk** [dperson/samba#408]
Hi,

I am getting these messages after I changed the location of shares

![image](https://user-images.githubusercontent.com/96798778/152790431-485e80c9-0279-4428-8d90-4b3dc7b3088b.png)

The one in red box was the old share and no longer in my compose

```
today at 12:37:29make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:29make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:29make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:29make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:39make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:39make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:39make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:39make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:39make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:39make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:39make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:39make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:39make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
today at 12:37:39make_connection_snum: canonicalize_connect_path failed for service Kratos, path /Kratos
```

You know how I can fix this?

```
  samba:
    image: dperson/samba
    hostname: ${DOCKERHOSTNAME}
    ports:
      - 139:139
      - 445:445
    container_name: samba
    environment:
      - GROUPID=${PGID}
      - TZ=${TZ}
      - USERID=${PUID}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}      
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/kratos/.docker/compose:/compose
      - ${DOCKERCONFDIR}:/config
      - ${DOCKERSTORAGEDIR}:/storage:slave
    command: -s "compose;/compose;yes;no;yes;all" -s "config;/config;yes;no;yes;all" -s "storage;/storage;yes;no;yes;all" 
```

Thank you
