### ISSUE TITLE
chdir_current_service: vfs_ChDir(/data) failed: Permission denied

### ISSUE THREAD

**Issue by AntoineGlacet** [dperson/samba#409]
Hi!

I am having an error I cannot understand. I try to connect from a PC on Windows to a container on Rpi4/Ubuntu-20.04 64 bits.
I am having the error on the title and I am clueless as to why.

here is my docker-compose file:
```
services:
  samba:
    container_name: samba
    image: dperson/samba
    volumes:
      - ${DATA}:/data
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    command: >
      samba.sh
        -s "rpi4;/data;yes;no;yes;all"
        -u "bob;1234"
    restart: unless-stopped
```

My PC workgroup is WORKGROUP, even if I add the option, I get the same error
