### ISSUE TITLE
Cannot mount as RW(readwrite) on macOS, but Windows works

### ISSUE THREAD

**Issue by greatbody** [dperson/samba#411]
I have problems mount this share as RW on my macOS device.

# Basic Infro

## Server

```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

## Docker

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  compose: Docker Compose (Docker Inc., v2.1.1)

Server:
 Containers: 12
  Running: 12
  Paused: 0
  Stopped: 0
 Images: 15
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.63-v7l+
 Operating System: Raspbian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 7.663GiB
 Name: raspberrypi
 ID: D7RF:7H4D:2D5X:QI7I:URIB:PDRV:HGHN:BJ5T:GPF7:F4T2:QQ7T:5WTI
 Docker Root Dir: /mnt/photos/docker-storage/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
```

# My docker compose

```
version: '3.0'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'EST5EDT'
    network_mode: "host"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/download/shows:/mnt/seagate3t
    command: '-n -S -s "publicshare;/mnt;yes;no;yes;all;" -p'
```

# Expectation

I am expecting to setup an Samba service that can be accessd without password and any one can have Read Write access.

As this service is working in my home network, security is not a problem.

# Problem

My Windows PC can access this Samba share and can R/W files and folders.

**But** my macOS can only mount is as Readonly.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/6984599/156107714-d3c93ac8-cf28-459b-a26f-fa2f8dd42ee9.png">
