### ISSUE TITLE
Question about config

### ISSUE THREAD

**Issue by killmasta93** [dperson/samba#414]
HI
Currently need to configure a docker samba for a printer which only has smbv1 to scan 

i was reading the wiki but could not figure out how to configure it,
as the printer needs one user called scanner with full access and other user to only read that folder I was thinking maybe like this?

but cant seem to create the docker compose file correctly this is what i have so far

```
version: '3.4'

services:
  samba:
    image: dperson/samba
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /folder/mnt2:/mnt2:z
    command: '-S "-s "scan;/mnt2;yes;no;no;scaner" -u "scaner;mypassword" -p'
    command: '-S "-s "scan;/mnt2;yes;yes;no;user" -u "user;mypassword" -p'
networks:
```
