### ISSUE TITLE
Duplicate shared vols after renaming a volume followed by recreating its container

### ISSUE THREAD

**Issue by LiyuCode** [dperson/samba#416]
The steps below leads to duplicated vols showing in Windows File Manager.

### Samba Server
 - OS: Ubuntu 20.04 LTS (Newly Installed)
### Windows Client
 - OS: Windows 10 Pro

## Steps to reproduce
1. Install docker & docker-compose
2. Using the `docker-compose.yml` file below to create and start an dperson/samba container
```yml
version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: vm_samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/ubuntu/samba:/mnt/sb1:z
    command: '-s "ReadOnly1;/mnt/sb1;yes;yes;yes;all;ubuntu;ubuntu" -u "ubuntu;ubuntu" -p'

networks:
  default:
```
3. Using Windows to open the Samba service, showing there is one folder named 'ReadOnly1'.
4. Renaming the name, "ReadyOnly1", in the `docker-compose.yml`, to "ReadOnly2"
5. Executing `docker stop vm_samba` and then `docker-compose -f docker-compose.yml up -d` to stop and restart the container.
6. Using Windows to reopen the Samba service, showing there are two folders, 'ReadOnly1' and 'ReadOnly2'.

Emm.. isn't the expcected result is there is only one folder, named 'ReadOnly2'?
