### ISSUE TITLE
Can't delete files/folders on Windows client

### ISSUE THREAD

**Issue by LiyuCode** [dperson/samba#422]
Hi everyone, 

## Setup

1. OS: `Ubuntu 20.04.5 LTS` (GNU/Linux 4.4.194+ aarch64)
2. CPU: Rockchip RK3399
3. Dockerfile:
The content of the Dockerfile, `docker-compose.yml`, used to create the Docker container is:
```
version: '3.4'

services:
  samba:
    image: dperson/samba:latest
    container_name: bcrk_samba
    environment:
      TZ: 'EST5EDT'
      SAMBA_HOSTS_ALLOW: '192.168.3.0/24'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime
      - /docker_data/bcrk_samba/samba_vols/public_ro:/samba_vols/public_ro:z
      - /docker_data/bcrk_samba/samba_vols/public_wx:/samba_vols/public_wx:z
      - /docker_data/bcrk_samba/samba_vols/user_MY_USERNAME:/samba_vols/user_MY_USERNAME:z
    command: >
        -S -w "WORKGROUP" 
        -s "Public Resources;/samba_vols/public_ro;yes;yes;yes;all;none;MY_USERNAME;Publicly readable" 
        -s "Temp Netdisk;/samba_vols/public_wx;yes;no;yes;all;MY_USERNAME;MY_USERNAME;Publicly writable" 
        -s "MY_USERNAME;/samba_vols/user_MY_USERNAME;yes;no;no;MY_USERNAME;MY_USERNAME;MY_USERNAME;For user MY_USERNAME only" 
        -u "MY_USERNAME;MY_SMBPWD" 
        -p

networks:
  default:
```

4. The command to initiate the container
It's  `sudo docker-compose -f docker-compose.yml up -d` 

## The intention of the container:
The Dockerfile is intended to create a Samba servers that:
 1. Only accessible from the IPs of `192.168.3.0/24`
 2. Has a folder named `Public Resources` which is writable only to the user `MY_USERNAME` , but is readable publicly/anonymously. 
 3. Has a folder named `Temp Netdisk` which is readable & writable to everyone publicly(anonymously).
 4. Has a folder named `MY_USERNAME` which is readable & writable to the user `MY_USERNAME` only. No access to everyone else.
 
## The problem
From an Windows 10 client, found:
 1. can't delete files/folders under all 3 folders.

However, the following are fine:
 1. the rights of reading are works as intended.
 2. the rights of writing works, although the Windows will prompt `Error: 0x80070032: unsupported request` when creating a folder, but after refreshing, the folder will be there, and copying files to the folders are fine.

## What has been tried to fix the problem
  1. After searching, found a post, https://github.com/dperson/samba/issues/364, is very close to the problem, so tried adding `-g` command but no luck.

What did I missed?
