### ISSUE TITLE
Unable to access server. Clear text password displayed to client

### ISSUE THREAD

**Issue by leeahoward** [dperson/samba#428]
I have used this image in the past, but having issues with a new setup.  It acts as if it's not parsing the user name and password provided in the USER env. It's treating the entire "username;password" value as the username. 

Attempt to connect using smbclient from within container:
```
bash-5.0# smbclient //uploads/uploads
Enter WORKGROUP\nwahec_user;cleartextpassword password: 
```

Dockerfile:
```
  uploads:  
    restart: unless-stopped  
    image: dperson/samba  
    ports:  
      - "137:137/udp"  
      - "138:138/udp"  
      - "139:139/tcp"  
      - "445:445/tcp"  
    restart: unless-stopped  
    environment:  
      TZ: America/New_York
      USERID: 101  # host jenkins user
      GROUPID: 101  # host jenkins group
      PERMISSIONS: "true"
      WORKGROUP: workgroup  
      # USER: ""
      USER: nwahec_user;cleartextpassword
      RECYCLE: "false"
      SHARE: uploads;/uploads;yes;no;no;nwahec_user;;;AHEC Uploads Folder

    volumes:  
      - uploads:/uploads
  ```
