### ISSUE TITLE
Signal 11 / panic errors (Docker, Portainer)

### ISSUE THREAD

**Issue by ghost** [dperson/samba#429]
Everything appears to be working fine, but the logs show the following errors over and over, every few seconds:

```
INTERNAL ERROR: Signal 11 in pid 54 (4.12.2)
If you are running a recent Samba version, and if you think this problem is not yet fixed in the latest versions, please consider reporting this bug, see https://wiki.samba.org/index.php/Bug_Reporting
===============================================================
PANIC (pid 54): internal error
unable to produce a stack trace on this platform
coredump is handled by helper binary specified at /proc/sys/kernel/core_pattern

```

I'm running this as a Portainer stack with the following docker compose:

```
version: '3.4'

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: 'EST5EDT'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /storage/media/tv:/tv:z
      - /storage/media/movies:/movies:z
    
    command: '-s "TV;/tv;yes;no;no;[redacted]" -s "Movies;/movies;yes;no;no;[redacted]" -u "[redacted];[redacted]" -p'
```

I mean it's working so I'm not super concerned except that it seems like something that shouldn't be happening. Any thoughts?
