### ISSUE TITLE
Connect to smb server problem

### ISSUE THREAD

**Issue by alice36** [dperson/samba#430]
I have below docker compose with samba image:

```
version: '3.7'

services:
  samba:
    image: dperson/samba
    platform: linux/x86_64
    command: -p -u "admin;password" -s "data;/mnt/data;yes;no;no;admin"
    restart: always
    hostname: my-hostname
    volumes:
      - type: bind
        source: /tmp
        target: /mnt/data
    ports:
      - "139:139"
      - "445:445"
    environment:
      - USERID=82
      - GROUPID=82
```

and logs:

Added user admin.
chown: /mnt/data/powerlog: Operation not permitted
chown: /mnt/data/powerlog: Operation not permitted
chmod: /mnt/data: Operation not permitted
chmod: /mnt/data/powerlog: Operation not permitted
smbd version 4.12.2 started.
Copyright Andrew Tridgell and the Samba Team 1992-2020
daemon_ready: daemon 'smbd' finished starting up and ready to serve connections

smb is ready to serve connection but in what way I can access it?

I tried:

smb://localhost
smb:/0.0.0.0
smb://127.0.0.1
smb://host.docker.internal

all without success, could you please advise?
And by the way how to fix this permission problem (chown: /mnt/data/powerlog: Operation not permitted)?
