### ISSUE TITLE
How i can mappeed folder backup in docker composer?

### ISSUE THREAD

**Issue by johndiego** [dperson/samba#44]
**
I liked just ready only no autentications folder backup, how i can solved this?
**
Tks advanced!

![image](https://cloud.githubusercontent.com/assets/18476845/23190470/ccab83e8-f876-11e6-9d55-b761d65d8902.png)

```
version: '2'
services:
    server:
        build: ./server
        image: pnick
        container_name: backend
        command: python  manage.py  runserver 0.0.0.0:8000
        volumes:
            - ./server:/server
        ports:
            - "8000:8000"
    samba:
        image: dperson/samba
        command: -u "root;root" -s "server/backup:yes;yes"
        restart: always
        ports:
            - "139:139"
            - "445:445"


```

**Comment by dperson** [comment]
It sounds like you want to have the same local storage that's passed into your python app shared by samba. If that's the case, the below should work (note I also fixed a typo in your share setup `-s`):
```
    samba:
        image: dperson/samba
        command: -u "root;root" -s "backup;/server/backup:yes;yes"
        restart: always
        ports:
            - "139:139"
            - "445:445"
        volumes:
            - ./server:/server
```
