### ISSUE TITLE
Samba libpopt.so.0 errors 

### ISSUE THREAD

**Issue by addohm** [dperson/samba#442]
I've recently had to commission a new NAS and am running into an issue with the following error:
```
Error loading shared library libpopt.so.0: Exec format error (needed by /usr/sbin/smbd)
Error loading shared library libpopt.so.0: Exec format error (needed by /usr/lib/samba/libpopt-samba3-samba4.so)
```
The logs are inundated with with this and only this.  The only things I can find anywhere near this error are a decade old or gentoo specific.  The only thing I can think of is that its running debian 12.  I didn't have this issue on a previously commissioned server running ubuntu server running jammy jellyfish.

**uname -a**
`Linux levenas 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.37-1 (2023-07-03) x86_64 GNU/Linux`

**lsb_release**
```
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```
**cat /etc/os-release**
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**docker compose file**
```yaml
version: '3.3'

services:
  samba:
    container_name: samba
    image: dperson/samba:latest
    environment:
      PUID: '1000'
      PGID: '1000'
      USERID: '1000'
      GROUPID: '1000'
      PERMISSIONS: 'true'
      USER: '${USER};${PASS}'
      TZ: 'America/New_York'
    networks:
      - default
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./data:/share:z
    command: '-s "fileshare;/share;yes;no;yes;${USER}" -u "${USER};${PASS}"'
    hostname: samba
```
