### ISSUE TITLE
/usr/bin/samba.sh: line 160: $2: unbound variable

### ISSUE THREAD

**Issue by alrapine** [dperson/samba#445]
My docker-compose file:

```
version: "3.3"
services:
  samba:
    container_name: samba
    image: dperson/samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=${TZ}"
    env_file: .env
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 250M
#         pids: 1
        reservations:
          cpus: '0.35'
          memory: 240M
    volumes:
      - /home/srv:/srv
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
    # -s "<name;/path>[;browse;readonly;guest;users;admins;writelist;comment]" 
    # -s "name;/path;no;no;no;example1"
      -s "srv;/srv;yes;no;yes"
      -p
```
got error `/usr/bin/samba.sh: line 160: $2: unbound variable`
