### ISSUE TITLE
Samba Server exit with HP Printer

### ISSUE THREAD

**Issue by hartmann-daniel** [dperson/samba#451]
Hello.

I've been struggling with Samba and an HP multifunction printer (OfficeJet Pro 9020) for a long time. My goal is to use the scanner to scan into an SMB drive. The SMB drive is a mounted WEBDAV directory from a Nextcloud. This means I can scan directly into the Nextcloud using a scanner. I have been using this project in Debian for several years. Since I have moved my Nextcloud to Docker containers, I also want to implement my scanning solution accordingly. Unfortunately, I fail with a self-made container and the one provided here.

Everything works perfectly when Windows 10 accesses the share. When accessing SMB2 via the HP multifunction printer, the SMB server crashes.

I suspect that there are rights problems between the container and the host system, but I can't really interpret the logs. Can anyone possibly help?

`Server exit (NT_STATUS_END_OF_FILE)`

Here is the log from smb:
[Log.txt](https://github.com/dperson/samba/files/13789227/Log.txt)

My Docker-Compose file:
```
version: '3'
services:
    samba:
        image: dperson/samba
        restart: unless-stopped
        ports:
            - "445:445"
            - "139:139"
        environment:
           SHARE: "scan;/tmp;yes;no;yes"
           SMB: true
           TZ: "Europe/Berlin"
           GLOBAL: "log level = 5"
```
