### ISSUE TITLE
Even with guest=yes, windows still ask for password

### ISSUE THREAD

**Issue by shalak** [dperson/samba#455]
Here's my configuration:

```yaml
  samba:
    image: dperson/samba
    container_name: samba
    network_mode: host
    environment:
      TZ: 'Europe/Warsaw'
      NMBD: true
      GROUPID: 1000
      USERID: 1000
      WORKGROUP: WORKGROUP
    read_only: true
    env_file:
      - samba.env  # contains SMB_PASSWORD
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /srv/storage/install/:/mnt:z
      - /srv/storage/public/:/mnt-public:z
    command: '-s "instalki;/mnt;yes;yes;yes;;;;instalatory" -s "instalki-public;/mnt-public;yes;no;yes;mirek,guest;mirek;mirek,guest;instalatory-publiczne" -s "instalki-rw;/mnt;yes;no;no;mirek" -u "mirek;$$SMB_PASSWORD" -p'
```

Unfortunately, when I enter `\\servername` in windows explorer, it immediately asks for password. Even though, it should allow guest access to `instalki` and `instalki-public` shares (with `instalki-public` having guest write pemissions), and only when trying to access `instalki-rw` it should prompt for password.

I even tried starting the container with only single share via `-s "instalki;/mnt;yes;yes;yes"` and it still prompted for credentials...

What am I missing?
