### ISSUE TITLE
Samba server can not be discovered in the network neighborhood

### ISSUE THREAD

**Issue by nachopro** [dperson/samba#69]
Hi! I'm running this container with -n

Bound ports:
```
0.0.0.0:139->139/tcp,
0.0.0.0:137-138->137-138/udp,
0.0.0.0:445->445/tcp
```

docker logs -f MY_CONTAINER_NAME:
```
[2017/08/21 00:11:58.179096,  0] ../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
  *****
  
  Samba name server KELLER is now a local master browser for workgroup WORKGROUP on subnet 172.17.0.2
```

Windows and GVFS-SMB's based client can't discover the server, but they can connects to direct IP: smb://192.168.x.x

When I ping "keller" on Windows it resolves to 172.17.0.2 but no response found :(
Whe I ping 172.17.0.2 from drocker's host works ok.

I don't understand how to map or route (if I must) this IP.

Can you helpme?
Thanks!

Related #59 ?

**Comment by nachopro** [comment]
Set the _interfaces_ parameter in smb.conf does not works :(
`bind failed on port 137 socket_addr`

**Comment by kevinchiang** [comment]
I'm running into this issue, too. I have this as the command:
`-ns Folder;/Folder;yes;no;yes`

**Comment by dperson** [comment]
If you're getting errors binding ports, it means that they're already in use. Something running on the system is using the port already.

**Comment by nachopro** [comment]
Sorry but the Samba (nmd) is broadcasting to 172.17.0.x no to 192.168.x.x, where the network neighborhood is listening. Ergo Windows nor Linux can discovery the container's shares.

Need I set some special binding between host and container?

Thanks foy our time

**Comment by htkoca** [comment]
Is network mode set to host? Not sure if that helps but that's how I have
it set up

https://github.com/htkoca/scripts-bash/blob/master/release/apps/docker/samba/local/docker-compose.yml

Tony Ko
+1-647-300-9787
www.htko.ca

**Comment by dperson** [comment]
@nachopro Can you confirm that the work around from @htkoca works? I'll add it to the documentation.

I don't really use `nmbd` so don't have much familiarity with troubleshooting it. Thank you both.

**Comment by nachopro** [comment]
@htkoca @dperson sorry for the delay :1st_place_medal: 

Using `--network host` works fine :) Thank you

```bash
[2018/07/12 17:30:04.132715,  0] ../lib/util/become_daemon.c:124(daemon_ready)
  STATUS=daemon 'nmbd' finished starting up and ready to serve connections
smbd version 4.7.6 started.
Copyright Andrew Tridgell and the Samba Team 1992-2017
STATUS=daemon 'smbd' finished starting up and ready to serve connections
[2018/07/12 17:30:27.261894,  0] ../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
  *****
  
  Samba name server KELLER is now a local master browser for workgroup MYGROUP on subnet 172.17.0.1
  
  *****
[2018/07/12 17:30:27.262336,  0] ../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
  *****
  
  Samba name server KELLER is now a local master browser for workgroup MYGROUP on subnet 192.168.77.6
  
  *****
```

**Comment by zhenwenc** [comment]
Hi, I am having similar issue like this, nmbd doesn't binds to host network. Here is my config:

```
version: '2.2'
services:
  samba:
    image: dperson/samba
    container_name: samba
    restart: unless-stopped
    healthcheck:
      disable: true
    network_mode: host
    ports:
      - 137:137
      - 138:138
      - 139:139
      - 445:445
    volumes:
      - ~/Downloads/:/downloads
    environment:
      - TZ=${TZ:-Pacific/Auckland}
      - PUID=${PUID}
      - PGID=${PGID}
      - NMBD=yes
      - RECYCLE=false
      - USER=admin;pass
      - WORKGROUP=WORKGROUP
      - SHARE=downloads;/downloads;yes;no;yes;;admin
```

```
samba    | [2019/11/30 05:18:08.691234,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
samba    |   *****
samba    |
samba    |   Samba name server SAMBA is now a local master browser for workgroup WORKGROUP on subnet 172.17.0.1
samba    |
samba    |   *****
samba    | [2019/11/30 05:18:08.691610,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
samba    |   *****
samba    |
samba    |   Samba name server SAMBA is now a local master browser for workgroup WORKGROUP on subnet 172.18.0.1
samba    |
samba    |   *****
samba    | [2019/11/30 05:18:08.692423,  0] ../../source3/nmbd/nmbd_become_lmb.c:397(become_local_master_stage2)
samba    |   *****
samba    |
samba    |   Samba name server SAMBA is now a local master browser for workgroup WORKGROUP on subnet 172.21.0.1
samba    |
samba    |   *****
```

Could anyone please give me some hints? Thanks!
