### ISSUE TITLE
GROUPID not used

### ISSUE THREAD

**Issue by Archcry** [dperson/samba#79]
I am trying to setup the following, I have a folder with `media:media` permissions, which translates to `1002:1002`. Now I set up the container with environment variables `-e USERID=1002` and `-e GROUPID=1002` and start with the `-p` parameter which sets the permissions on the directory.

Now when I check the permissions it changed it to `1002:100`, the userid is correct but the groupid is ignored.

```
  samba:
    image: dperson/samba
    container_name: samba
    volumes:
      - /home/media/share:/mount/share
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139
      - 445:445
    environment:
      - NMBD=true
      - USERID=1002
      - GROUPID=1002
      - WORKGROUP=WORKGROUP
    command: -u "media;<secret>" -s "share;/mount/share;yes;no;no;media;media" -p
```
